ccflags-y := -std=gnu99 -Wno-declaration-after-statement
obj-y	+= firmware/
obj-y	+= serial/
obj-y   += pci/
obj-y   += disk/
obj-y   += ../thread/switch.o
obj-y   += timer.o
obj-y   += ../thread/thread.o
obj-y   += ../lib/kernel/list.o
obj-y   += ../lib/kernel/bitmap.o

