obj-y				+= efi-stub-helper.o mem.o printk.o vsprintf.o

obj-$(CONFIG_EFI_GENERIC_STUB)	+= efi-stub-entry.o systable.o screen_info.o efi-stub.o

obj-$(CONFIG_X86)		+= x86-stub.o
obj-$(CONFIG_LOONGARCH)		+= loongarch.o loongarch-stub.o
